### ISSUE TITLE
How to read error from flutter iframe?

### ISSUE THREAD

**Issue by softmarshmallow** [dart-lang/dart-pad#1668] opened 2020-11-08 09:29 UTC
Displaying runtime errors will be a helpful feature, since it does not, and show nothing instead.

How to access iframe's error from parent web js?

**Comment by softmarshmallow** [comment] 2020-11-08 09:57
Maybe we can add errback on requirejs for loading flutter_sdk.js and flutter_web.js

https://stackoverflow.com/a/18739787/5463235

**Comment by RedBrogdon** [comment] 2020-11-15 04:16
Do you mean runtime errors caused by the executed code, or runtime errors within DartPad itself?

**Comment by softmarshmallow** [comment] 2020-11-15 04:36
Yes, for example when there is only one color in gradient, on mac, it will draw and tell us what wen't wrong. but on dartpad, the error is always same as "Stack Regex matching failed ..." and it also does not draws anything.

Just telling users that something went wrong will be very helpful. so they won't wait for munites for their code to be drawn. (which is already executed with error, drawn nothing)

**Comment by RedBrogdon** [comment] 2020-11-15 04:52
Got it. We've got an open issue for improved exception reporting, but haven't had the time to get it done: #1365. I'm closing this as a duplicate, but will make a note for prioritization.

**Closed by RedBrogdon** 2020-11-15 04:52 UTC
Labels: p2

**Comment by softmarshmallow** [comment] 2020-11-15 05:23
Thanks!
