### ISSUE TITLE
Console doesn't show error messages

### ISSUE THREAD

**Issue by InMatrix** [dart-lang/dart-pad#1618] opened 2020-08-23 21:44 UTC
## What happened?

I was trying to create a demo of a Flutter runtime error on DartPad, but the Console only displays "Script error" instead of the actual error message.

## Steps to reproduce problem

Run this DartPad: https://dartpad.dev/2a8e855da8cf3aca24c912ac54c9876c

### Browser

Browser: Chrome 

Version: Version 84.0.4147.135 (Official Build) (64-bit)

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)? I don't think so.

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

![image](https://user-images.githubusercontent.com/348942/90989492-f3e06280-e54e-11ea-83c2-b7a7b43bc57e.png)

### Machine

Operating system: Mac OS X 

Version: 10.15.6

**Comment by guidezpl** [comment] 2020-08-25 18:23
Found similar warnings trying to run a code sample

<details><summary>sample</summary>
<p>

```dart
// Copyright (c) 2019, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return
    TextField(
      textAlign: TextAlign.end,
      decoration: InputDecoration(
        floatingLabelBehavior: FloatingLabelBehavior.always,
        suffixText: 'USD',
        labelText: 'Value',
        hintText: '0,00',
      ),
    );
   
  }
}

```

</p>
</details>

<img width="896" alt="Screen Shot 2020-08-25 at 8 18 55 PM" src="https://user-images.githubusercontent.com/6655696/91212269-4452ee00-e710-11ea-82a0-7de40e6fbd8b.png">

**Comment by johnpryan** [comment] 2021-02-25 01:06
This also happens with `throw()`:

```
void main() {
  throw('foo');
}
```

**Comment by johnpryan** [comment] 2022-10-06 00:20
Duplicate of https://github.com/dart-lang/dart-pad/issues/1365

**Closed by johnpryan** 2022-10-06 00:20 UTC
Labels: bug, p2, error messaging
