### ISSUE TITLE
uncaught exceptions cut off in dartpad console?

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dart-pad#823] opened 2018-05-30 21:51 UTC
A simple case of throwing an uncaught exception results in very little being displayed.  We just get the word "Uncaught".

![screenshot from 2018-05-30 14-51-00](https://user-images.githubusercontent.com/14116827/40749430-e1e4ed26-6418-11e8-89a7-62dcb4c7d302.png)

**Comment by devoncarew** [comment] 2018-05-31 01:54
Yes, it's not very helpful. Closing as a duplicate of https://github.com/dart-lang/dart-pad/issues/737, but we should re-triage the dartpad issues, and assign some important ones to a for-next-release milestone.

**Closed** 2018-05-31 01:54 UTC
