### ISSUE TITLE
Website demo doesn't work

### ISSUE THREAD

**Issue by mfu-goodmonday** [dart-lang/dart-pad#1788] opened 2021-03-14 22:12 UTC
The demo "Try Flutter in your browser" on the Flutter front page
fails with the following error

    Error: Assertion failed: file:///Users/brettmorgan/Documents/GitHub/dart-services/flutter-sdk/packages/flutter/lib/src/rendering/mouse_tracking.dart:332:12 (event is PointerAddedEvent) == (lastEvent is PointerRemovedEvent) is not trueError: Error: Assertion failed: file:///Users/brettmorgan/Documents/GitHub/dart-services/flutter-sdk/packages/flutter/lib/src/rendering/mouse_tracking.dart:332:12 (event is PointerAddedEvent) == (lastEvent is PointerRemovedEvent) is not true

**Comment by domesticmouse** [comment] 2021-03-14 23:56
Can you please give more detail? Which operating system (and version) are you using, which browser (and version) are you viewing the page with? Which sample are you attempting to run?

All three samples work for me on macOS 11.2.3 (20D91), Google Chrome	89.0.4389.82 (Official Build) (x86_64).

**Comment by mfu-goodmonday** [comment] 2021-03-15 18:40
It starts now, but FYI, it throws some errors

Fibonacci
`Error: Assertion failed: file:///Users/brettmorgan/Documents/GitHub/dart-services/flutter-sdk/packages/flutter/lib/src/rendering/mouse_tracking.dart:332:12
(event is PointerAddedEvent) == (lastEvent is PointerRemovedEvent)
is not trueError: Error: Assertion failed: file:///Users/brettmorgan/Documents/GitHub/dart-services/flutter-sdk/packages/flutter/lib/src/rendering/mouse_tracking.dart:332:12
(event is PointerAddedEvent) == (lastEvent is PointerRemovedEvent)
is not true`

Counter
`Error: Assertion failed: file:///Users/brettmorgan/Documents/GitHub/dart-services/flutter-sdk/packages/flutter/lib/src/rendering/mouse_tracking.dart:332:12
(event is PointerAddedEvent) == (lastEvent is PointerRemovedEvent)
is not trueError: Error: Assertion failed: file:///Users/brettmorgan/Documents/GitHub/dart-services/flutter-sdk/packages/flutter/lib/src/rendering/mouse_tracking.dart:332:12
(event is PointerAddedEvent) == (lastEvent is PointerRemovedEvent)
is not true`

**Comment by domesticmouse** [comment] 2021-03-15 23:39
Hey @mariamhas, I'm guessing we are using Flutter for Web incorrectly somehow. Who should I talk with?

**Comment by mariamhas** [comment] 2021-03-30 23:33
adding platform-web tag so this can get triaged by the team

**Comment by johnpryan** [comment] 2021-03-31 17:13
I can't reproduce this - I see a lot of `dart.developer.registerExtension ext.flutter.activeDevToolsServerAddress` but no errors in the console.

**Comment by RedBrogdon** [comment] 2021-04-11 00:08
I'm also unable to reproduce this. Closing for now, but folks should feel free to reopen if it's still an issue.

**Closed by RedBrogdon** 2021-04-11 00:08 UTC

**Comment by mozerrr** [comment] 2021-09-13 15:22
Hi, found this issue again.
If I change to flow [example](https://api.flutter.dev/flutter/widgets/Flow-class.html#widgets.Flow.1) code will work. But my example isn't.

```
/// Flutter code sample for Flow

// This example uses the [Flow] widget to create a menu that opens and closes
// as it is interacted with, shown above. The color of the button in the menu
// changes to indicate which one has been selected.

import 'package:flutter/material.dart';

void main() => runApp(const FlowApp());

class FlowApp extends StatelessWidget {
  const FlowApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Flow Example'),
        ),
        body: Row(children: [FlowMenu(), Text('yest')]),
      ),
    );
  }
}

class FlowMenu extends StatefulWidget {
  const FlowMenu({Key? key}) : super(key: key);

  @override
  State<FlowMenu> createState() => _FlowMenuState();
}

class _FlowMenuState extends State<FlowMenu>
    with SingleTickerProviderStateMixin {
  late AnimationController menuAnimation;
  IconData lastTapped = Icons.notifications;
  final List<IconData> menuItems = <IconData>[
    Icons.home,
    Icons.new_releases,
    Icons.notifications,
    Icons.settings,
    Icons.menu,
  ];

  void _updateMenu(IconData icon) {
    if (icon != Icons.menu) {
      setState(() => lastTapped = icon);
    }
  }

  @override
  void initState() {
    super.initState();
    menuAnimation = AnimationController(
      duration: const Duration(milliseconds: 250),
      vsync: this,
    );
  }

  Widget flowMenuItem(IconData icon) {
    final double buttonDiameter =
        MediaQuery.of(context).size.width / menuItems.length;
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8.0),
      child: RawMaterialButton(
        fillColor: lastTapped == icon ? Colors.amber[700] : Colors.blue,
        splashColor: Colors.amber[100],
        shape: const CircleBorder(),
        constraints: BoxConstraints.tight(Size(buttonDiameter, buttonDiameter)),
        onPressed: () {
          _updateMenu(icon);
          menuAnimation.status == AnimationStatus.completed
              ? menuAnimation.reverse()
              : menuAnimation.forward();
        },
        child: Icon(
          icon,
          color: Colors.white,
          size: 45.0,
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Flow(
      delegate: FlowMenuDelegate(menuAnimation: menuAnimation),
      children:
          menuItems.map<Widget>((IconData icon) => flowMenuItem(icon)).toList(),
    );
  }
}

class FlowMenuDelegate extends FlowDelegate {
  FlowMenuDelegate({required this.menuAnimation})
      : super(repaint: menuAnimation);

  final Animation<double> menuAnimation;

  @override
  bool shouldRepaint(FlowMenuDelegate oldDelegate) {
    return menuAnimation != oldDelegate.menuAnimation;
  }

  @override
  void paintChildren(FlowPaintingContext context) {
    double dx = 0.0;
    for (int i = 0; i < context.childCount; ++i) {
      dx = context.getChildSize(i)!.width * i;
      context.paintChild(
        i,
        transform: Matrix4.translationValues(
          dx * menuAnimation.value,
          0,
          0,
        ),
      );
    }
  }
}
```
error:
```
Error: Assertion failed: file:///Users/brettmorgan/Documents/GitHub/dart-services/flutter-sdk/packages/flutter/lib/src/foundation/stack_frame.dart:114:12
match != null
"Expected DartError@https://storage.googleapis.com/nnbd_artifacts/2.14.0/dart_sdk.js:6780:7 to match RegExp/^(.+) (\\d+):(\\d+)\\s+(.+)$/."Error: Error: Assertion failed: file:///Users/brettmorgan/Documents/GitHub/dart-services/flutter-sdk/packages/flutter/lib/src/foundation/stack_frame.dart:114:12
match != null
"Expected DartError@https://storage.googleapis.com/nnbd_artifacts/2.14.0/dart_sdk.js:6780:7 to match RegExp/^(.+) (\\d+):(\\d+)\\s+(.+)$/."
```
