### ISSUE TITLE
Add support for `cross_file` plugin

### ISSUE THREAD

**Issue by m0nac0** [dart-lang/dart-pad#2070] opened 2021-11-07 19:12 UTC
It would be great if the [cross_file plugin](https://pub.dev/packages/cross_file) could be added to the list of supported packages. Since it's an official plugin by the flutter team, it hopefully shouldn't raise security concerns.

**Comment by domesticmouse** [comment] 2021-11-07 20:40
@m0nac0 I'm curious what your intended use case is for this package.

/cc @srawlins

**Comment by m0nac0** [comment] 2021-11-08 12:47
I'm experimenting with generating code for Flutter apps and found DartPad to be a very cool way to preview both the generated code and the resulting app. Since the code I'm generating should ultimately run on different platforms I chose the cross_file plugin for file operations.

I guess the bigger question here is, whether there are any formal criteria or a selection process for the packages getting included DartPad. Since I couldn't find anything on that, I thought I'd just ask ;)

**Comment by RedBrogdon** [comment] 2021-11-09 01:40
> whether there are any formal criteria or a selection process for the packages getting included DartPad. Since I couldn't find anything on that, I thought I'd just ask ;)

We still haven't stamped "finished" on package support, which is why the process hasn't been documented. Our current draft plan is to handle it the way most of Flutter prioritizes new features: people file an issue requesting a particular package, other people moderate it with thumb's up or thumb's down, and we use those as a primary input.

One thing I should add is that we're probably going to go more slowly than people would expect. DartPad is a weird execution environment, and we essentially have to hand-verify every package/plugin.

**Comment by m0nac0** [comment] 2021-11-09 16:27
Sounds good, thank you for the explanation!

**Comment by domesticmouse** [comment] 2022-01-31 02:14
I'm curious what use case you have in mind for the `cross_file` plugin. Looking at the description of the plugin, I can't see how this would be useful inside the DartPad environment. Halp?

**Comment by johnpryan** [comment] 2023-01-12 22:04
Closed in #995

**Comment by domesticmouse** [comment] 2023-01-12 22:35
Actually, this isn't shipped to production, so re-opening this bug. This package has been shipped to our hidden testing instance https://dartpad.dev/?channel=dev

Please exercise your suggested package on this instance and confirm here that it works as intended. If you do confirm this as working I'll ship it to `stable`, `beta`, `master`, and `old` channels on dartpad.dev. If you don't confirm, I won't ship it.

**Closed** 2023-01-25 10:03 UTC
Labels: p2, packages, suggested-package
