### ISSUE TITLE
Error compiling to JavaScript: TimeoutException after 0:00:20.000000: Future not completed

### ISSUE THREAD

**Issue by amisare** [dart-lang/dart-pad#833] opened 2018-07-11 11:02 UTC
Dartpad server is blocked in China. Is there any plan to change server or build a mirror server in China?

**Comment by kevmoo** [comment] 2018-10-17 21:34
@jcollins-g any idea why this is happening?

At a minimum, it'd be nice to have a better error message...

**Comment by kevmoo** [comment] 2018-10-17 21:36
Duplicate of #851

**Closed by kevmoo** 2018-10-17 21:36 UTC
Labels: bug
