### ISSUE TITLE
Please add light theme

### ISSUE THREAD

**Issue by Topbrains** [dart-lang/dart-pad#1791] opened 2021-03-15 12:43 UTC
The default dark theme forces users to turn brightness up to see things in gray and blue. You are violating Material design guidelines on visibility (contrast).

Please provide a light theme or adjust the colors for contrast.

**Comment by johnpryan** [comment] 2021-03-15 23:30
Duplicate of https://github.com/dart-lang/dart-pad/issues/1643

**Closed by johnpryan** 2021-03-15 23:30 UTC
