### ISSUE TITLE
Feature: Allow Flutter Version Pinning

### ISSUE THREAD

**Issue by jascodes** [dart-lang/dart-pad#1622] opened 2020-08-27 16:13 UTC
It will be nice feature dartpad service allow multiple sdk versions and version of sdk is persisted in the gist itself. I might be the case you want to place if at .fvm/fvm_config.json based on tool https://github.com/leoafarias/fvm
This helps manage multiple versions sdk and allow pinning file in fvm_config.json. 
```
// fvm_config.json
{"flutterSdkVersion":"1.20.2"}
```

**Comment by domesticmouse** [comment] 2020-08-29 08:02
This requires running multiple versions of the compilers and analyzers in the prod cluster. Currently we only run 1 version of each.

**Comment by domesticmouse** [comment] 2020-08-29 22:38
This is a feature I’d like to implement, and is part of the motivation to migrate to Cloud Run. Keeping this feature open as a tracker.

**Comment by domesticmouse** [comment] 2021-02-08 03:59
Re-reading this request, the request is for a specific version. With the current Cloud Run infra this would require provisioning a DNS record per version to be able to address a version specific Cloud Run backend. I'm not a fan of going down that route.

My preference is instead to do three Cloud Run backends, one for `stable`, one for `beta` and one for `dev`.

**Comment by jascodes** [comment] 2021-02-08 08:02
Well that's still better then nothing I guess...

**Comment by RedBrogdon** [comment] 2021-02-08 17:29
> My preference is instead to do three Cloud Run backends, one for stable, one for beta and one for dev.

I think we have general agreement on this idea. Want to either retitle this bug or close it and create a new one to represent the work needed to get the three channels up and running? There'd be both backend work and front-end, since we'd need some kind of UI for switching versions.

**Comment by jascodes** [comment] 2021-02-08 19:58
@RedBrogdon Feel free to do whatever you feel like

**Comment by RedBrogdon** [comment] 2021-02-09 01:55
Looks like we're already tracking this at #774. I'll close this as a duplicate of that one.

**Closed by RedBrogdon** 2021-02-09 01:55 UTC
Labels: dart-services, p3
