### ISSUE TITLE
Text widget with foreground Paint in TextStyle is not working

### ISSUE THREAD

**Issue by AAAbramenko** [dart-lang/dart-pad#1647] opened 2020-10-11 16:59 UTC
Text widget with foreground Paint in TextStyle is not working in Chrome (no info about other browsers):
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Stack(
            children: <Widget>[
              // Stroked text as border.
              Text(
                'Greetings, planet!',
                style: TextStyle(
                  fontSize: 40,
                  foreground: Paint()
                    ..style = PaintingStyle.stroke
                    ..strokeWidth = 6
                    ..color = Colors.blue[700],
                ),
              ),
              // Solid text as fill.
              Text(
                'Greetings, planet!',
                style: TextStyle(
                  fontSize: 40,
                  color: Colors.grey[300],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
Shows "Script error".
Stack with text widget is got from [TextStyle docs](https://api.flutter.dev/flutter/painting/TextStyle-class.html).

**Comment by domesticmouse** [comment] 2020-10-13 05:49
Console error log:

```
Uncaught Error: Assertion failed: file:///Users/brettmorgan/Documents/GitHub/dart-services/flutter/packages/flutter/lib/src/foundation/stack_frame.dart:114:12
match != null
"Expected Error: Assertion failed: file:///Users/brettmorgan/Documents/GitHub/dart-services/flutter/packages/flutter/lib/src/foundation/stack_frame.dart:114:12 to match RegExp/^(.+) (\\d+):(\\d+)\\s+(.+)$/."
    at Object.throw_ [as throw] (dart_sdk.js:4328)
    at Object.assertFailed (dart_sdk.js:4275)
    at Function._parseWebDebugFrame (flutter_web.js:279794)
    at Function._parseWebFrame (flutter_web.js:279784)
    at MappedIterator.new.fromStackTraceLine (flutter_web.js:279828)
    at MappedIterator.new.moveNext (dart_sdk.js:21490)
    at WhereTypeIterator.new.moveNext (dart_sdk.js:22551)
    at JsIterator.next (dart_sdk.js:5997)
    at Function.from (dart_sdk.js:43902)
    at Function.of (dart_sdk.js:43917)
    at WhereTypeIterable.new.toList (dart_sdk.js:19581)
    at Function.fromStackString (flutter_web.js:279779)
    at Function.fromStackTrace (flutter_web.js:279771)
    at assertions.FlutterErrorDetails.new.debugFillProperties (flutter_web.js:275407)
    at flutter_web.js:275843
    at assertions._FlutterErrorDetailsNode.new.get builder (flutter_web.js:275846)
    at assertions._FlutterErrorDetailsNode.new.get builder [as builder] (flutter_web.js:275910)
    at assertions._FlutterErrorDetailsNode.new.getProperties (flutter_web.js:275858)
    at diagnostics$.TextTreeRenderer.new.[_debugRender] (flutter_web.js:277793)
    at diagnostics$.TextTreeRenderer.new.render (flutter_web.js:277704)
    at Function.dumpErrorToConsole (flutter_web.js:275533)
    at flutter_web.js:275683
    at Function.reportError (flutter_web.js:275638)
    at binding$.WidgetsFlutterBinding.new.[_invokeFrameCallback] (flutter_web.js:307829)
    at binding$.WidgetsFlutterBinding.new.handleDrawFrame (flutter_web.js:307792)
    at flutter_web.js:307706
    at internalCallback (dart_sdk.js:23761)
```

**Comment by domesticmouse** [comment] 2020-10-13 05:54
Running this locally on master channel, works as intended on macOS, but fails when using Chrome as target platform.

```
The following RenderObject was being processed when the exception was fired: RenderParagraph#6030b relayoutBoundary=up3
RenderObject: RenderParagraph#6030b relayoutBoundary=up3
    parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
    constraints: BoxConstraints(0.0<=w<=1200.0, 0.0<=h<=904.0)
    size: MISSING
    textAlign: start
    textDirection: ltr
    softWrap: wrapping at box width
    overflow: clip
    locale: en_US
    maxLines: unlimited
    text: TextSpan
        debugLabel: ((englishLike body1 2014).merge(blackCupertino bodyText2)).merge(unknown)
        inherit: false
        family: .SF UI Text
        size: 40.0
        weight: 400
        baseline: alphabetic
        foreground: Paint(PaintingStyle.stroke 6; Color(0xff1976d2))
        decoration: TextDecoration.none
        "Greetings, planet!"
════════════════════════════════════════════════════════════════════════════════
```

**Comment by domesticmouse** [comment] 2020-10-13 06:14
Running this with the [CanvasKit backend](https://github.com/flutter/flutter/wiki/Experimental-flags-for-web-support#canvaskit-backend) gives a result without a stack trace, but it is also visually incorrect.

**Comment by domesticmouse** [comment] 2020-10-13 06:26
Transferred to flutter/flutter.

**Closed by domesticmouse** 2020-10-13 06:26 UTC
