### ISSUE TITLE
DartPad is on an old (buggy) version of Dart2/Dart2JS

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/dart-pad#840] opened 2018-07-23 19:24 UTC
Including a version of Dart2JS that (accidentally) omits covariance checks.

You can see one such example of confusion here:
https://github.com/dart-lang/sdk/issues/33947

It would be very beneficial to update ASAP.

/cc @srawlins

**Comment by jcollins-g** [comment] 2018-07-24 16:44
this is known.  currently blocked on dart-lang/dart-services#343

**Comment by srawlins** [comment] 2018-07-24 17:22
Accidentally closed?

**Comment by matanlurey** [comment] 2018-07-24 17:22
I realize this is functionally the same as https://github.com/dart-lang/dart-services/issues/343, but it's pretty confusing since I think nobody not on the Dart infrastructure team would know `dart-services` is the same as "DartPad".

(Maybe this is an argument to make a mono repo with all of the "dart infra" pieces, though?)

**Comment by jcollins-g** [comment] 2018-07-24 17:33
Yep, it is confusing, which is why I referenced the issue it is a duplicate of and marked this as "duplicate" before closing it.

**Closed by jcollins-g** 2018-07-24 17:33 UTC
Labels: duplicate

**Comment by srawlins** [comment] 2018-07-24 18:05
Oops, didn't see the duplicate tag. Thanks!

**Comment by jcollins-g** [comment] 2018-07-26 18:18
FYI:  https://jcollins1-debug-dot-dart-pad.appspot.com/ is pointing to a dart-services backend with dart-lang/dart-services#344, if you'd like to try it.  Blocking issues finally cleared out of the way.
