### ISSUE TITLE
UI hangs on infinite loops

### ISSUE THREAD

**Issue by adanilo** [dart-lang/dart-pad#2302] opened 2022-06-16 02:26 UTC
## What happened?
Naive user codes an infinite loop and clicks 'Run' causes the entire UI to lock up.
It should be possible to click reset or similar to get back to a usable state.

## Steps to reproduce problem
1) Load up DartPad in a browser tab.
2) Write an infinite loop, e.g.:
  void main() {
    int i = 0;
    while (i < 5) {
      print('Hello $i');
    }
  }
3) Click 'Run'.

Expected result:
The string 'Hello 0' should get printed continuously.

Actual result:
DartPad hangs, user can't click 'Reset' or anything, must reload the browser tab to recover.

### Browser

Browser: Chrome

Version: 102.0.5005.61 (stable)

### Machine

Operating system: OS X

Version: 12.4

**Comment by johnpryan** [comment] 2022-10-06 00:30
Thanks for filing an issue, this is a known problem and should definitely be fixed at some point. Other tools in the JS ecosystem do a better job here.

Duplicate of https://github.com/dart-lang/dart-pad/issues/1522

**Comment by johnpryan** [comment] 2022-10-06 00:30
Duplicate of https://github.com/dart-lang/dart-pad/issues/1522

**Closed by johnpryan** 2022-10-06 00:30 UTC
