### ISSUE TITLE
Recursive infinite method calls, page not responding

### ISSUE THREAD

**Issue by DavidPerezContreras** [dart-lang/dart-pad#2226] opened 2022-04-07 16:03 UTC
## What happened?

In an anonymous async function I called main method, from main method (recursively)

### Browser

Browser: Microsoft Edge(iOS)

Version: 99.0.1150.52

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

No

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:
No

```
[paste warnings or errors here]
```

### Machine

Operating system:iOS

Version:14.8.1

### Your code

I can't paste code because The page is not responding 😂 here's an image.

![image](https://user-images.githubusercontent.com/91068383/162246624-fd124c4c-2827-432c-94aa-ff5449900291.png)

**Comment by johnpryan** [comment] 2022-10-06 00:29
Closing as a duplicate of https://github.com/dart-lang/dart-pad/issues/1522

**Comment by johnpryan** [comment] 2022-10-06 00:29
Duplicate of https://github.com/dart-lang/dart-pad/issues/1522

**Closed by johnpryan** 2022-10-06 00:29 UTC
