### ISSUE TITLE
we need the Old Version of Dart pad 

### ISSUE THREAD

**Issue by samouch** [dart-lang/dart-pad#2892] opened 2024-03-06 16:22 UTC
new dart pad Problems : 
** shortCuts keys alt+enter dsnt work ,
** refresh the page destroy the old code ,
** Documentation about methods or data type dsnt show as before

**Comment by gregslusarski** [comment] 2024-03-06 22:55
I would also add, that at least for me (win 10, chrome), after using autocompletion 'ctrl+space', enter, space and tab keys are broken. For example enter and space, opens up samples menu, or toggles brightness, instead of doing what they should

**Comment by Vaibhav77e** [comment] 2024-03-07 05:51
Yes we need old version dartpad this version lags too much and won't render or gives output just the page will load forever

**Comment by fdemiguel** [comment] 2024-03-08 06:57
> I would also add, that at least for me (win 10, chrome), after using autocompletion 'ctrl+space', enter, space and tab keys are broken. For example enter and space, opens up samples menu, or toggles brightness, instead of doing what they should

I fully agree. The current Dartpad is not functional

**Comment by Coffeer** [comment] 2024-03-30 04:10
Here's an improved version of the comment that maintains all the information while keeping it clear and concise:

The Dart editor on DartPad is experiencing several issues:

1. The dot operator (`.`) no longer triggers the pop-up that displays an object's properties and methods.
2. The Dart documentation panel on the right side is not showing up at all.
3. The screen has rendering issues:
   - Sometimes the code disappears from the editor.
   - The output does not render properly.

I have attempted the following troubleshooting steps, but the issues persist:

1. Added an exception to allow cookies for the DartPad URL.
2. Cleared the browser's cache and cookies.
3. Tested on both Google Chrome and Mozilla Firefox browsers.

Please investigate and resolve these issues to ensure a smooth and functional user experience on DartPad.

**Comment by Coffeer** [comment] 2024-03-30 04:11
The Dart editor on DartPad is experiencing several issues:

1. The dot operator (`.`) no longer triggers the pop-up that displays an object's properties and methods.
2. The Dart documentation panel on the right side is not showing up at all.
3. The screen has rendering issues:
   - Sometimes the code disappears from the editor.
   - Sometimes the output does not render.

I have attempted the following troubleshooting steps, but the issues persist:

1. Added an exception to allow cookies for the DartPad URL.
2. Cleared the browser's cache and cookies.
3. Tested on both Google Chrome and Mozilla Firefox browsers.

Please investigate and resolve these issues to ensure a smooth and functional user experience on DartPad.

**Comment by dantechguy** [comment] 2024-04-09 10:20
The old version still exists! I found it from #2838. The URL is now https://old-dartpad-3ce3f.web.app

**Comment by Coffeer** [comment] 2024-04-09 21:20
> The old version still exists! I found it from #2838. The URL is now https://old-dartpad-3ce3f.web.app

Awesome! Thanks for sharing!
The auto-complete feature is back, no more crashes so far, but the documentation is still not working for me on the newer version, so your link for the old version is helpful. 👍

**Comment by DimitrisAndreou** [comment] 2024-04-19 00:23
Much worse experience in the new dartpad :-( slow, print()s not reliably showing up, output font is weird. Worst of all: it doesn't reliably show up the error (e.g. applying the ! operator on null), it just fails silently.

**Comment by garawaa** [comment] 2024-06-04 12:43
It still did not fix it. On any browser it is toooooooooooooooo slow.

**Comment by johnpryan** [comment] 2024-06-18 21:16
Shortcuts should be working as intended now, and the docs panel has been implemented in the new version. I filed an issue to save the user's snippet to local storage. (https://github.com/dart-lang/dart-pad/issues/3016)

I'm going to close this since it's slightly out of date. Feel free to comment if you have more feedback on the new editor.

**Closed by johnpryan** 2024-06-18 21:16 UTC
Labels: type-ux, area-preview-ui
