### ISSUE TITLE
Add support for `dartz` package

### ISSUE THREAD

**Issue by brizaldi** [dart-lang/dart-pad#2362] opened 2022-09-19 09:31 UTC
[https://pub.dev/packages/dartz](https://pub.dev/packages/dartz)

**Comment by johnpryan** [comment] 2023-01-12 22:03
Fixed by #995

**Comment by domesticmouse** [comment] 2023-01-12 22:37
Actually, this isn't shipped to production, so I'm re-opening this issue. This package has been shipped to our hidden testing instance https://dartpad.dev/?channel=dev

Please exercise your suggested package on this instance and confirm here that it works as intended. If you do confirm this as working I'll ship it to `stable`, `beta`, `master`, and `old` channels on dartpad.dev. If you don't confirm, I won't ship it.

**Comment by brizaldi** [comment] 2023-01-13 01:39
@domesticmouse got this error when running the program with imported `dartz` package
```
Error compiling to JavaScript:
Info: Compiling with sound null safety
Error: Couldn't resolve the package 'dartz' in 'package:dartz/dartz.dart'.
lib/main.dart:1:8:
Error: Not found: 'package:dartz/dartz.dart'
import 'package:dartz/dartz.dart';
       ^
Error: Compilation failed.
```

**Comment by brizaldi** [comment] 2023-01-13 03:00
From the link above: https://dartpad.dev/?channel=dev

and here's the code:
```dart
import 'package:dartz/dartz.dart';

void main() {
  for (int i = 0; i < 5; i++) {
    print('hello ${i + 1}');
  }
}

```

**Comment by parlough** [comment] 2023-01-13 03:03
Looks like it was only added to supported Flutter packages @domesticmouse.

**Comment by domesticmouse** [comment] 2023-01-13 03:05
> Looks like it was only added to supported Flutter packages @domesticmouse, not Dart.

Good catch, I'll roll up a fix up PR

**Comment by domesticmouse** [comment] 2023-01-13 03:21
PR: https://github.com/dart-lang/dart-services/pull/996

**Comment by domesticmouse** [comment] 2023-01-16 07:41
The import works now =)

**Comment by brizaldi** [comment] 2023-01-16 11:25
Thanks @domesticmouse, can confirm that it's working perfectly 👍

**Closed** 2023-01-25 10:03 UTC
Labels: suggested-package
