### ISSUE TITLE
Support selecting channel in Flutter embeds

### ISSUE THREAD

**Issue by guidezpl** [dart-lang/dart-pad#2409] opened 2022-11-08 06:59 UTC
I recently ran into samples which don't run on the Flutter master channel API docs pages (https://master-api.flutter.dev). For example, https://dartpad.dev/embed-flutter.html?split=60&run=true&null_safety=true&sample_id=material.Switch.3&sample_channel=master. `sample_channel=master` here seems to affect the docs, but not the Flutter SDK version. 

https://dartpad.dev/?channel=master is already supported, so this request is for embeds.

**Comment by johnpryan** [comment] 2022-11-09 19:13
DartPad supports the `channel` parameter in embeds, I think the issue is that there's both the `sample_channel` and `channel` parameters. See [this comment](https://github.com/flutter/flutter/issues/114795#issuecomment-1309192617) - I'm going to close this, but feel free to comment if you're still seeing unexpected behavior

**Closed by johnpryan** 2022-11-09 19:13 UTC
