### ISSUE TITLE
Disable line wrapping

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1342] opened 2019-10-23 16:48 UTC
DartPad currently uses line wrapping, but this causes some weird behavior for samples with long lines. For example, an upcoming codelab uses this line:

```
const owl_url =
    'https://raw.githubusercontent.com/flutter/website/master/src/images/owl.jpg';
```

This line of code restricts the size of the Flutter app.

**Comment by johnpryan** [comment] 2019-11-12 00:39
The second sample at https://dart.dev/tutorials/web/low-level-html/add-elements also demonstrates this issue

**Comment by RedBrogdon** [comment] 2020-01-02 18:00
@johnpryan Should #1438 be considered a duplicate of this issue?

**Comment by johnpryan** [comment] 2020-01-02 18:07
Yeah, marked that issue as a dupe. Pasting the gist from that issue for reference: https://dartpad.dartlang.org/cbb4deb6b52b3cb7689d2fb974cf9c58

**Comment by theacodes** [comment] 2021-02-17 19:02
It's also visible here: https://flutter.dev/docs/codelabs/layout-basics_migrated#image-widget

**Comment by theacodes** [comment] 2021-02-17 19:08
We should probably put a `min-width` property on the output container as well.

**Comment by marcellodesales** [comment] 2021-06-16 02:56
Any workarounds here?

**Comment by johnpryan** [comment] 2021-06-16 03:04
@marcellodesales see https://github.com/dart-lang/dart-pad/pull/1921

**Comment by marcellodesales** [comment] 2021-06-16 03:52
I came up with a groovy string to generate a variable with the long string value :) 

https://groovyconsole.appspot.com/script/5151226664583168

**Closed** 2021-06-17 13:20 UTC
Labels: p2, polish
