### ISSUE TITLE
Animations in DartPad are buggy

### ISSUE THREAD

**Issue by legalcodes** [dart-lang/dart-pad#1223] opened 2019-08-21 21:47 UTC
Staged:
https://jt-flutter-website-1.firebaseapp.com/docs/codelabs/implicit-animations

We've tested these animations in iOS simulator and they work perfectly. 
After using them in DartPad, we noticed that clicking the button in the UI that is supposed to trigger the animation doesn't actually consistently start the animation (it can take several clicks before the animation finally kicks in).

![implicit_animations](https://user-images.githubusercontent.com/5550175/63470877-9b99f080-c422-11e9-965b-33517a59ed44.gif)

**Comment by johnpryan** [comment] 2019-08-21 22:34
I'm also seeing the issue when I go to https://jt-flutter-website-1.firebaseapp.com/docs/codelabs/implicit-animations but if I load that sample in a standalone version it works normally: https://dartpad.dev/experimental/embed-new-flutter.html/b81b8c4ca51cceac01d29326f7bf6349

**Comment by legalcodes** [comment] 2019-08-22 20:37
I dont think the issue is limited to animations. See also: 

[Standalone version](https://dartpad.dev/experimental/embed-new-flutter.html?id=e7f05290e2adf6864571cecbcb10429e) (works)

[Embedded version](https://jt-flutter-website-1.firebaseapp.com/docs/codelabs/implicit-animations) (Try the "counter" example, which doesn't work)

**Comment by ditman** [comment] 2019-08-22 21:24
I'm not entirely sure, but the only times I've seen this is when the iframe where the flutter app is running considers that it's in a "cross-domain" scenario.

This may get triggered by silly things, like attempting to see if you're inside an iframe or not, but I can't pinpoint exactly what's triggering it in this case. Have you tried removing the `sandbox` attribute from the flutter iframe?

**Comment by johnpryan** [comment] 2019-08-22 21:38
@ditman FWIW we are using the latest version of https://github.com/flutter/flutter_web to build the iframe. In fact, it's an iframe *within an iframe* (DartPad itself runs FFW in an iframe) that's behaving slow.

**Comment by johnpryan** [comment] 2019-08-22 21:40
We can look into removing the sandbox attribute

**Comment by ditman** [comment] 2019-08-22 21:41
Yes, the two inner iframes shouldn't have any cross-domain issues because they're served from the same domain (the innermost even has a relative URL). I'm concerned about the `sandbox` attribute on the innermost one.

I'm currently trying to repro this behavior with a super simple app in my box.

**Comment by johnpryan** [comment] 2019-08-23 17:09
I think this is a Flutter for web issue, so I've filed an issue to keep track: https://github.com/flutter/flutter/issues/39127

**Comment by legalcodes** [comment] 2019-08-23 18:55
Closing, per above this is being tracked in flutter/flutter#39127

**Comment by RedBrogdon** [comment] 2019-09-03 21:48
This has been confirmed as fixed by the Chrome team in M77. We can close the issue.

**Closed by RedBrogdon** 2019-09-03 21:48 UTC
Labels: bug, p0
