### ISSUE TITLE
stdin.readLineSync() consistently generates "Uncaught" error.

### ISSUE THREAD

**Issue by thinklog** [dart-lang/dart-pad#775] opened 2017-06-16 19:07 UTC
The following sample code generates an Uncaught error in DartPad

import 'dart:io';

void main() {
  print("Your input please:");
  String yourInput=stdin.readLineSync();
  print(yourInput);
}

See dartpad here:
https://dartpad.dartlang.org/343e1d447505b6048e317948f3733bf8

**Comment by matanlurey** [comment] 2017-06-16 19:11
[DartPad does not support `dart:io`](https://www.dartlang.org/dart-vm):

> Note: DartPad does not support using dart:io APIs or importing libraries from packages.

Dupe of https://github.com/dart-lang/dart-pad/issues/3.

**Closed by matanlurey** 2017-06-16 19:11 UTC
Labels: duplicate
