### ISSUE TITLE
[Feature] Ability to use multiple 'Pads'

### ISSUE THREAD

**Issue by KristofKekesi** [dart-lang/dart-pad#1661] opened 2020-10-29 18:35 UTC
## Ability to use and save multiple 'Pads'
As I know it uses local storage (cookies) to store the current project, so I think this idea would be feasible.

**Comment by KristofKekesi** [comment] 2020-10-29 18:36
similar like #1654

**Comment by RedBrogdon** [comment] 2020-11-15 04:02
I'm going to close this as a duplicate of #1654, since they both relate to the same feature. Thanks for filing the request, @KristofKekesi!

**Closed by RedBrogdon** 2020-11-15 04:02 UTC
