### ISSUE TITLE
Async bug when re-run (Stream not cleared?)

### ISSUE THREAD

**Issue by justinmc** [dart-lang/dart-pad#2246] opened 2022-04-18 18:22 UTC
When listening to a Stream, it doesn't get cleared between runs and continues to operate.

https://dartpad.dartlang.org/?id=ed7088d267f42e590ca38cabab8fcf50

To reproduce:

1. Run the example. "the item is number n" is correctly printed every 500ms.
2. Change either of the strings.
3. Run again.

Expected: Only the new string is printed on every tick now.
Actual: Both old and new strings get printed.

<details>

<summary>Code from the dartpad example</summary>

```dart
void main() async {
  final Stream<String> stream = Stream<String>.periodic(
    const Duration(milliseconds: 500),
    (int count) => 'number $count',
  );
  
  await for (final String item in stream) {
    print('the item is: $item');
  }
}
```

</details>

**Comment by domesticmouse** [comment] 2022-04-18 21:16
John, can you confirm this is a result of not cleaning the Sandbox sufficiently?

**Comment by johnpryan** [comment] 2022-04-18 21:27
Duplicate of https://github.com/dart-lang/dart-pad/issues/1632

**Closed by johnpryan** 2022-04-18 21:27 UTC
