### ISSUE TITLE
result always is null

### ISSUE THREAD

**Issue by CathyChen0910** [dart-lang/dart-pad#985] opened 2019-04-04 04:21 UTC
whatever the left pad code contains , the right result always show null . Can't run normally

**Comment by RedBrogdon** [comment] 2019-04-04 04:38
Can you provide the code that you were trying to run (the contents of the left pad), so that we can replicate the issue?

Also, was this in the main DartPad UI (the one shown at dartpad.dartlang.org)?

**Comment by jwzhou93** [comment] 2019-04-04 05:15
I have the same issue, whatever the code typed, even the sample 'Hello World'

**Comment by kumarbv** [comment] 2019-04-04 06:18
Since morning, I am having the same problem. Multiple pads, multiple browsers used, but the problem persists...

**Comment by Waheed388** [comment] 2019-04-04 09:40
Same not working for me too. Just returning the null value. Does not matter even a simple for loop is returning null.
void main() {
  for (var i = 1; i <= 10; i++) {
    if (i == 5) {
      continue;
    }
    print(i);
  }
}

**Comment by anichijioke** [comment] 2019-04-04 10:35
is there no solution to the problems mentioned above? This is really fustrating

**Comment by kumarbv** [comment] 2019-04-04 10:54
I found out that one particular VM called 'Fibonacci' is working on the Safari version of the browser. This is intermittent, but after 2 - 3 times, it works. Try this VM please...

**Comment by danny3s** [comment] 2019-04-04 15:21
its always null, all the samples show null !!!!

**Comment by domesticmouse** [comment] 2019-04-04 15:22
I suspect this is a duplicate of https://github.com/dart-lang/dart-pad/issues/986

**Comment by RedBrogdon** [comment] 2019-04-04 15:25
We just rolled back a recent change and deployed a new version of DartPad. Those of you who've run into the null issue, could you try again in a few minutes and see if the problem persists?

If you still can't compile, please let us know the browser you're using. We suspect this may be an issue in the front-end code.

**Comment by devoncarew** [comment] 2019-04-04 15:43
Thanks for all the feedback; closing as a dup of #986.

**Closed by devoncarew** 2019-04-04 15:43 UTC
