### ISSUE TITLE
Dark theme menu text not readable

### ISSUE THREAD

**Issue by Kernix13** [dart-lang/dart-pad#2901] opened 2024-03-15 15:06 UTC
## What happened?

The menu items under the New button/menu, Samples button/menu, and the 3 vertical dots must have the same color as the background color because they are not visible. They also don't have tab focus but that is secondary. The icons show but the link text does not.

<img width="286" alt="image" src="https://github.com/dart-lang/dart-pad/assets/66497948/eac3449a-db0c-4fbb-a69f-5e99def1493a">

## Steps to reproduce problem

1. Switch to dark mode
2. Click on any of the menus to try and view the menu items
3. Switch to light mode to see the menu items

### Browser

Browser: Brave

Version: 1.63.174

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

I am using AdBlock but I disabled it for DartPAd and refreshed and the text is still not visible. My other extensions are Grammarly, JSON Formatter, Markdown Preview Plus, React Developer Tools, Redux DevTools, VisBug, and Wave Evaluation Tool.

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
canvaskit.js:129 WebGL: this extension has very low support on mobile devices; do not rely on it for rendering effects: WEBGL_polygon_mode
```

### Machine

Operating system: Windows

Version: 11

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```
// Paste code here.
```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```
[paste console output here]
```

If you were running Flutter code, you can also paste an image of the
Flutter output directly into this bug report.

**Comment by parlough** [comment] 2024-03-16 12:43
Thanks for opening an issue! Definitely a problem, that was caused by some recent changes to `ColorScheme` on the `main` channel.

I'm going to close this issue in favor of https://github.com/dart-lang/dart-pad/issues/2895 which tracks the same problem. I opened https://github.com/dart-lang/dart-pad/pull/2900 to resolve it :)

**Closed by parlough** 2024-03-16 12:43 UTC

**Comment by Kernix13** [comment] 2024-03-16 19:48
Sorry for the repetition of issues. I searched for "dark theme" and the same for light but did not see an issue so I created this one. Hope it's fixed soon because I prefer dark modes
