### ISSUE TITLE
 Error compiling to JavaScript: XMLHttpRequest error.

### ISSUE THREAD

**Issue by Yeikel200** [dart-lang/dart-pad#974] opened 2019-04-02 13:02 UTC
Hello, I get this error when I run the example that comes by default. I am behind a proxy, an alternative to solve this problem?

This is the log of the browser consolo:

`Failed to load resource: the server responded with a status of 403 ()
(index):1 Access to XMLHttpRequest at 'https://dart-services.appspot.com/api/dartservices/v1/version?alt=json' from origin 'https://dartpad.dartlang.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
2dart-services.appspot.com/api/dartservices/v1/analyze?alt=json:1 Failed to load resource: the server responded with a status of 403 ()
(index):1 Access to XMLHttpRequest at 'https://dart-services.appspot.com/api/dartservices/v1/analyze?alt=json' from origin 'https://dartpad.dartlang.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
main.dart.js:1170 [SEVERE] dartpad: XMLHttpRequest error.
2dart-services.appspot.com/api/dartservices/v1/compile?alt=json:1 Failed to load resource: the server responded with a status of 403 ()
(index):1 Access to XMLHttpRequest at 'https://dart-services.appspot.com/api/dartservices/v1/compile?alt=json' from origin 'https://dartpad.dartlang.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
(index):1 Failed to decode downloaded font: https://fonts.gstatic.com/stats/Roboto/normal/400
2main.dart.js:8715 POST https://dart-services.appspot.com/api/dartservices/v1/compile?alt=json 403
aO @ main.dart.js:8715
wR @ main.dart.js:1317
(anonymous) @ main.dart.js:12824
(anonymous) @ main.dart.js:1392
$2 @ main.dart.js:5836
$1 @ main.dart.js:5828
em @ main.dart.js:6929
$0 @ main.dart.js:6246
dX @ main.dart.js:1503
dg @ main.dart.js:6139
$0 @ main.dart.js:6207
yL @ main.dart.js:1533
yR @ main.dart.js:1535
$1 @ main.dart.js:5780
zo @ main.dart.js:542
(anonymous) @ main.dart.js:551
childList (async)
$1 @ main.dart.js:5787
vp @ main.dart.js:1541
dg @ main.dart.js:1642
rI @ main.dart.js:1560
cf @ main.dart.js:6695
fz @ main.dart.js:6498
fF @ main.dart.js:6425
dk @ main.dart.js:6474
S @ main.dart.js:6645
S @ main.dart.js:6364
la @ main.dart.js:12887
(anonymous) @ main.dart.js:12807
(anonymous) @ main.dart.js:1392
$2 @ main.dart.js:5836
i7 @ main.dart.js:1374
aO @ main.dart.js:12843
aO @ main.dart.js:11205
$0 @ main.dart.js:9842
jK @ main.dart.js:9808
(anonymous) @ main.dart.js:9765
(anonymous) @ main.dart.js:1392
$2 @ main.dart.js:5836
i7 @ main.dart.js:1374
l5 @ main.dart.js:9790
a9 @ main.dart.js:9759
ke @ main.dart.js:12267
cr @ main.dart.js:11510
$1 @ main.dart.js:11660
$1 @ main.dart.js:9110
zo @ main.dart.js:542
(anonymous) @ main.dart.js:551
(index):1 Access to XMLHttpRequest at 'https://dart-services.appspot.com/api/dartservices/v1/compile?alt=json' from origin 'https://dartpad.dartlang.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by domesticmouse** [comment] 2019-04-02 20:13
I suspect your proxy is breaking things, because `https://dart-services.appspot.com/api/dartservices/v1/compile?alt=json` is indeed sending appropriate CORS headers.

**Comment by RedBrogdon** [comment] 2019-04-10 22:43
Closing this for now. If you can reproduce this outside that particular network, please let us know.

**Closed by RedBrogdon** 2019-04-10 22:43 UTC

**Comment by shreyash333** [comment] 2020-05-20 09:39
Hey i am Getting the same error

**Comment by domesticmouse** [comment] 2020-05-22 11:55
Yeah, we had another outage. We have updated the mitigation to roll the servers even more frequently, so this should, hopefully, be less of an issue going forward.
