### ISSUE TITLE
Add support for `riverpod_navigator`

### ISSUE THREAD

**Issue by PavelPZ** [dart-lang/dart-pad#2174] opened 2022-02-22 09:57 UTC

**Comment by johnpryan** [comment] 2023-01-12 22:04
Closed in #995

**Comment by domesticmouse** [comment] 2023-01-12 22:36
Actually, this isn't shipped to production, so I'm re-opening this issue. This package has been shipped to our hidden testing instance https://dartpad.dev/?channel=dev

Please exercise your suggested package on this instance and confirm here that it works as intended. If you do confirm this as working I'll ship it to `stable`, `beta`, `master`, and `old` channels on dartpad.dev. If you don't confirm, I won't ship it.

**Closed** 2023-01-25 10:03 UTC
Labels: suggested-package
