### ISSUE TITLE
Need option to show line numbers

### ISSUE THREAD

**Issue by Topbrains** [dart-lang/dart-pad#1790] opened 2021-03-15 12:39 UTC
Please add a configuration option to show line numbers.

**Comment by johnpryan** [comment] 2021-03-15 23:29
This is a duplicate of https://github.com/dart-lang/dart-pad/issues/317, but the good news is someone submitted a PR: https://github.com/dart-lang/dart-pad/pull/1789, which should be merged soon.

**Closed by johnpryan** 2021-03-15 23:29 UTC
