### ISSUE TITLE
Output Window gets squeezed up to the right, instead of wrapping up the code, when longer strings are used 

### ISSUE THREAD

**Issue by Sparsh1212** [dart-lang/dart-pad#1617] opened 2020-08-21 18:30 UTC
## What happened?

On using strings/lines of code which are considerably longer in the dart pad, the output window squeezes and is not visible at all. The user has to move the bottom horizontal scroll bar every time, to view the output window.

## Steps to reproduce problem

Just paste the code which I have attached below. You can see that the output window is squeezed to the right and is barely visible.
![image](https://user-images.githubusercontent.com/55937724/90922397-955d9c00-e409-11ea-9fe0-1b5a8be952c4.png)

### Browser

Browser:

Version:

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
[paste warnings or errors here]
```

### Machine

Operating system:

Version:

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var title = 'Web Images';

    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
        body: Image.network(
          'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAARQAAAEUCAYAAADqcMl5AAAAAklEQVR4AewaftIAABH9SURBVO3BQY4YybLgQDJR978yR0tfBZDIKKnfHzezP1hrrQse1lrrkoe11rrkYa21Ln'
        ),
      ),
    );
  }
}

```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

when I tried to wrap the string by pressing the **Enter** key after some portion of the string, I got the following errors in the console:
```
error
Too many positional arguments: 1 expected, but 3 found - line 16
error
Unterminated string literal - line 17
error
Undefined name 'a21Ln' - line 18
error
Expected to find ',' - line 18
error
Unterminated string literal - line 18
error
Expected to find ',' - line 18
```

![image](https://user-images.githubusercontent.com/55937724/90922072-ffc20c80-e408-11ea-83ce-40f4e90584bf.png)

If you were running Flutter code, you can also paste an image of the
Flutter output directly into this bug report.

**Comment by RedBrogdon** [comment] 2020-08-25 04:23
Thanks for filing an issue @Sparsh1212. It looks like this is a duplicate of #1342, a bug related line wrapping that we haven't found the bandwidth to fix. I'm going to close this one, but will reference it in the other issue.

**Closed by RedBrogdon** 2020-08-25 04:23 UTC
