### ISSUE TITLE
Add support for `creator` package

### ISSUE THREAD

**Issue by terryl1900** [dart-lang/dart-pad#2288] opened 2022-06-02 20:36 UTC
Hello, [`Creator`](https://github.com/terryl1900/creator) is a state management package I recently released. It is inspired by rivperpod.

Currently, I'm copying all the source code to make DartPad work ([example](https://dartpad.dev/?id=a6d82a6bb955fa4f42ff50b6c6d90d34)), and I would like to request native DartPad support.

Not sure what is the criteria here. I guess my package is still too early? Anyway, creating this issue to track.

**Comment by iamshaunwu** [comment] 2022-07-29 20:45
+1

**Comment by mukhtharcm** [comment] 2022-09-03 12:29
+1

**Comment by johnpryan** [comment] 2023-01-12 22:04
Closed in #995

**Comment by domesticmouse** [comment] 2023-01-12 22:37
Actually, this isn't shipped to production, so I'm re-opening this issue. This package has been shipped to our hidden testing instance https://dartpad.dev/?channel=dev

Please exercise your suggested package on this instance and confirm here that it works as intended. If you do confirm this as working I'll ship it to `stable`, `beta`, `master`, and `old` channels on dartpad.dev. If you don't confirm, I won't ship it.

**Comment by terryl1900** [comment] 2023-01-19 16:56
Hi @domesticmouse I confirm it works on the testing instance. Thank you!

**Comment by domesticmouse** [comment] 2023-01-19 21:56
Thank you @terryl1900!

**Closed** 2023-01-25 10:03 UTC
Labels: suggested-package
