### ISSUE TITLE
improve caching of the dart_sdk.js file

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#2786] opened 2024-01-05 17:36 UTC
Every time we run an app, we re-request `https://storage.googleapis.com/nnbd_artifacts/3.2.3/dart_sdk.js`, a 1.8MB file. We should improve the caching here.

**Comment by parlough** [comment] 2024-01-05 17:41
Ah I forgot to bring this up when we met. If I'm understanding the Network view correctly, it seems most calls in the iframe aren't pulling from the disk or memory cache.

This is in Chrome, Firefox does seem to do a better job of pulling from the cache. So I wonder if it has to do with Chrome's iframe sandboxing?

**Comment by johnpryan** [comment] 2024-01-08 18:09
There are a other files that could be cached here, canvaskit.js is another file we request after each compilation.

**Comment by parlough** [comment] 2024-06-17 20:06
Closing as a duplicate of https://github.com/dart-lang/dart-pad/issues/2493

**Closed by parlough** 2024-06-17 20:06 UTC
Labels: type-performance, area-preview-ui
