### ISSUE TITLE
after clicking enter it's just switching the theme

### ISSUE THREAD

**Issue by rootUJ99** [dart-lang/dart-pad#2891] opened 2024-03-05 05:12 UTC
## What happened?

while using dartpad latest version whenever I'm pressing enter button it's just changing the theme and not really taking it as return key in editor

### Browser

Browser: brave

Version: 1.63.165

### Machine

Operating system: macOS

Version: 14.2.1

**Comment by skylon07** [comment] 2024-03-06 16:23
To add a little bit of info here, I run into this a lot because I hit [Tab] to indent code. It seems the tab keypress isn't being captured by the input field, which causes the browser to cycle through focusing on the elements around the page. Then, because the input field is no longer focused, hitting [Enter], [Space], etc. causes unexpected and jarring behavior.

Workaround: Rapidly smash your spacebar and be grateful for VSCode 😆
(And if you do hit [Tab] accidentally, copy your code, reload, and paste -- the site doesn't save your code automatically at the moment, see #2871)

**Comment by skylon07** [comment] 2024-03-06 16:28
And funny enough, I have nearly identical specs -- hello fellow Brave user!

**Comment by parlough** [comment] 2024-03-30 00:56
Thanks for the issue and all of the details! Sorry about the degraded experience here.

I'm going to close this issue as a duplicate of https://github.com/dart-lang/dart-pad/issues/2852 to consolidate discussion there.

**Closed by parlough** 2024-03-30 00:56 UTC
