### ISSUE TITLE
CORS error when running a flutter docs example

### ISSUE THREAD

**Issue by fischerscode** [dart-lang/dart-pad#2961] opened 2024-05-09 21:57 UTC
*I'm not sure if this is the correct repo to file this issue.*

## What happened?

When running a flutter docs example ([like this one](https://api.flutter.dev/flutter/widgets/Listener-class.html#widgets.Listener.1)), the app wont start and a CORS error is logged in the console.

## Steps to reproduce problem

1. Open [this](https://api.flutter.dev/flutter/widgets/Listener-class.html#widgets.Listener.1) page
2. "Inspect" the page to see the console
3. Click RUN
4. See the error

## Additional info

Disabling CORS restrictions using [cors everywhere](https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/) allows the example to run just fine.

### Browser

Browser: Firefox

Version: 125.0.3 (64-Bit)

```
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://dartpad.dev/canvaskit/canvaskit.wasm. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt). Statuscode: 200.
(English Translation: Cross-source (cross-origin) request blocked: The same-source rule prohibits reading the external resource at https://dartpad.dev/canvaskit/canvaskit.wasm. (Reason: CORS header 'Access-Control-Allow-Origin' is missing). Status code: 200.)

Rejecting promise with error: TypeError: NetworkError when attempting to fetch resource. js_util_patch.dart:110:65

Uncaught (in promise) null frame.js:35:47
```

### Machine

Operating system: Windows 11

Version: 23H2 (22631.3447)

### Your code

*See the example*

### DartPad's output

*Nothing*

![flutter_docs_example](https://github.com/dart-lang/dart-pad/assets/45403027/e08cc224-fa42-4078-bde6-08d49cffa814)

**Comment by devoncarew** [comment] 2024-05-09 22:22
cc @johnpryan 

We had a deploy today which did have CORS issues; we've since redeployed. Can you refresh the page and confirm that you still see the issue?

**Comment by fischerscode** [comment] 2024-05-10 10:55
@devoncarew I just tried it and still get the same CORS error. (Even after telling firefox to forget about this page.)

<details>
<summary>Response headers when `https://dartpad.dev/canvaskit/canvaskit.wasm` is called. (Maybe this helps.)</summary>
<pre class="notranslate"><code class="notranslate">HTTP/3 200 
content-length: 2119094
cache-control: max-age=3600
content-encoding: br
content-type: application/wasm
cross-origin-embedder-policy: credentialless
cross-origin-opener-policy: same-origin
cross-origin-resource-policy: cross-origin
etag: "dd53a08ac776faac61845f080f931aebd3909832e2e4702e5413871d75a22f75-br"
last-modified: Thu, 09 May 2024 19:44:48 GMT
referrer-policy: strict-origin-when-cross-origin
strict-transport-security: max-age=31556926
x-content-type-options: nosniff
accept-ranges: bytes
date: Fri, 10 May 2024 10:53:38 GMT
x-served-by: cache-fra-eddf8230135-FRA
x-cache: HIT
x-cache-hits: 1
x-timer: S1715338418.110123,VS0,VE6
vary: x-fh-requested-host, accept-encoding
alt-svc: h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400
</code></pre>
</details>

**Comment by shanecbauman** [comment] 2024-05-10 15:04
Im having the same issue. Tested on both firefox and chrome. Here are the console logs when the issue happens:
```
Null serviceWorker configuration. Skipping. flutter.js:1:2820
Injecting <script> tag. Using callback. flutter.js:1:1458
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://dartpad.dev/flutter.js
Source Map URL: flutter.js.map
unreachable code after return statement test_structure.dart:94:2
unreachable code after return statement test_structure.dart:172:2
Flutter Web Bootstrap: Programmatic. js_util_patch.dart:110:65
registerExtension() from dart:developer is only supported in build/run/test environments where the developer event method hooks have been set by package:dwds v11.1.0 or higher. developer_patch.dart:88:6
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://dartpad.dev/canvaskit/canvaskit.wasm. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.
Rejecting promise with error: TypeError: NetworkError when attempting to fetch resource. js_util_patch.dart:110:65
Uncaught (in promise) null frame.js:35:47

```

**Comment by johnpryan** [comment] 2024-05-10 16:00
I can't reproduce this anymore, I am able to run the [listener sample](https://api.flutter.dev/flutter/widgets/Listener-class.html#widgets.Listener.1) linked above on the latest version of DartPad. 

I'm going to close this for now, feel free to leave a comment if you are still seeing the issue.

**Closed by johnpryan** 2024-05-10 16:00 UTC

**Comment by fischerscode** [comment] 2024-05-10 16:37
On my system, it still fails. But it might be due to some cache somewhere... I'll retry it in a few hours.

**Comment by shanecbauman** [comment] 2024-05-10 16:41
It now works for me now on chrome, but firefox is still not working. I'm using windows 11.

**Comment by fischerscode** [comment] 2024-05-11 09:39
The [listener example](https://api.flutter.dev/flutter/widgets/Listener-class.html#widgets.Listener.1) has still a CORS issue on my firefox setup.

*Feel free to close this issue again.*

**Comment by fischerscode** [comment] 2024-05-15 21:17
Just realized it's now working for me on firefox. 👍

**Comment by shanecbauman** [comment] 2024-05-15 21:53
I just checked and its working for me on firefox also. Thanks!
