### ISSUE TITLE
DartPad's execution sandbox needs proper cleaning between runs.

### ISSUE THREAD

**Issue by angelhdzmultimedia** [dart-lang/dart-pad#1817] opened 2021-04-13 22:04 UTC
## What happened?
Timers (from dart:async, in an HTML project) don't stop after hitting RUN button. 

## Steps to reproduce problem
I create a a timer attached to a class private property, that when completes, checks if the looping property is true, then cancels the current timer, sets the property to null, and creates a new timer in the same property to continue the loop. When hitting RUN button on Dartpad to refresh the app, the timer is still running, even if I make a condition that if the timer is active when the app starts, cancels it.

It's like if the Refresh button fails (or not even make an attempt) to stop any active timer.

This doesn't happen on a pure HTML/JS project on repl.it or Codepen.

### Browser

Browser: Chrome

Version: 89.0.4389.114 (Official Build) (64-bit)

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?
**No**

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
[paste warnings or errors here]
```

### Machine

Operating system:
Windows 10 Pro

Version: 10.0.19042 Build 19042

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```
// Paste code here.
```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```
[paste console output here]
```

If you were running Flutter code, you can also paste an image of the
Flutter output directly into this bug report.
**No error. The only output is the print() calls of the Timer that refuses to die (😂).**

**Comment by domesticmouse** [comment] 2021-04-14 02:13
Please supply full repro case

**Comment by angelhdz** [comment] 2021-04-14 02:43
> Please supply full repro case

https://gist.github.com/angelhdz/245b81b674680bd94ba07ddbe2ce7c56

**Comment by domesticmouse** [comment] 2021-04-14 05:13
@RedBrogdon thoughts on this one? 

I suspect it's a case of not throwing away the sandbox container and thus enabling running javascript to stay in scope.

**Comment by angelhdz** [comment] 2021-04-15 16:52
### Update

I started a new project to modify the <style> from a static class. It has a Map and store the CSS attributes as keys and the body as the value, then, it finds the <style> tag with the id, and replace the inner html.

I noticed that sometimes when I change a CSS attribute and hit RUN, it doesn't reflect the changes, so I have to hit F5 to reload the whole page.

So, in my understanding, the issue is not about timers, it's about the process executed when hitting the RUN button, failing to dispose the current sandbox as @domesticmouse said.

I hope this gets solved since I'm using dartpad a lot lately, because I prefer Dart for working with the DOM instead of JavaScript.

Thanks guys, stay healthy, wishing you all success, cheers.

**Comment by RedBrogdon** [comment] 2021-05-03 22:18
> I suspect it's a case of not throwing away the sandbox container and thus enabling running javascript to stay in scope.

That's correct. It's been a known-but-minor issue for a while now.

Given that we also have a related issue that manifests when you run a Flutter app with null safety, then switch to non-null safe mode and try compiling something, we might want to start tossing the iframe contents and creating them anew.

**Comment by srawlins** [comment] 2021-05-07 16:33
@RedBrogdon with the hot reload issue you mentioned, can you think of a good heuristic for when we should destroy the iframe? In the case flagged for this bug, it seems very manual or "every time." Worth adding a button to the screen?

**Comment by RedBrogdon** [comment] 2021-05-07 22:55
I'd probably go with:

* Has a Firebase import been added or removed since the previous run?
* Has the null safety toggle been changed since the previous run?

**Comment by srawlins** [comment] 2021-05-08 04:55
@RedBrogdon That heuristic will work for the null safety toggle bug (I don't know if there is an actual issue number), but will not solve this issue. Should I implement something to solve this issue?

**Comment by jamesderlin** [comment] 2021-08-01 09:34
I'm confused.  When should pressing the "Run" button in DartPad *not* cancel all outstanding `Timer`s?

https://github.com/dart-lang/dart-pad/issues/1817#issuecomment-834601555 mentions hot reload and https://github.com/dart-lang/dart-pad/issues/1817#issuecomment-837629435 mentions hot restart.  Which is it?

If there's some way to do hot reload in DartPad (how?), then wouldn't that involve some explicit, separate "hot reload" button?

Or if https://github.com/dart-lang/dart-pad/issues/1817#issuecomment-837629435 did mean hot restart and not hot reload, then wouldn't we still want to cancel all outstanding `Timer`s in that case?  If some heuristic is needed because we might not want to destroy the iframe in some cases, then can we just cancel outstanding `Timer`s separately?

**Comment by RedBrogdon** [comment] 2021-08-02 21:57
For performance reasons, DartPad does not fully dispose and reload the iframe in which it executes non-Flutter Dart code when the Run button is hit n+1 times. Instead, it kills the previous script node and inserts a new one with the new code, then calls its entrypoint.

This makes it quicker, particularly for those on lower-end machines, to see the output of compiled code. The down side is that certain things, like Timers, can end up hanging around in between calls. This is an annoyance, but a rare one, so the decision was made to adopt the current behavior.

**Comment by parlough** [comment] 2024-06-17 02:29
This was originally fixed by https://github.com/dart-lang/dart-pad/pull/2270 and future improvements are tracked in https://github.com/dart-lang/dart-pad/issues/2269. Thanks again for the original report and related investigation!!

**Closed by parlough** 2024-06-17 02:29 UTC
Labels: P2
