### ISSUE TITLE
DartPad "Run" button covers code/comment directly under it

### ISSUE THREAD

**Issue by MoyinShabi** [dart-lang/dart-pad#1665] opened 2020-11-03 22:53 UTC
Here's a photo of the issue:
![Annotation 2020-11-03 233556](https://user-images.githubusercontent.com/21967002/98049023-2fd95300-1e2f-11eb-9c59-21193bc7a60e.png)
Part of the comment that starts on the first line in the DartPad gets covered by the "Run" button and this is the same case when I try to increase the size of my code editor screen. I hope this gets fixed for a much better user experience.

**Comment by shantanu1k** [comment] 2021-02-12 09:47
Is there any chance if we could place 'RUN' button on the appBar?

**Comment by shantanu1k** [comment] 2021-02-14 06:27
I want to work on this issue.

**Comment by MoyinShabi** [comment] 2021-02-14 18:54
> I want to work on this issue.

@RedBrogdon

**Comment by RedBrogdon** [comment] 2021-02-19 06:39
Hmm. It's certainly true that we could move the run button to the title bar, but that would increase the minimum width required fo DartPad embeds, and it would be a significant design change.

There may be other options as well, such as collapsing the button to a single icon, then expanding it on mouse over to reveal the full text.

@johnpryan, I know you worked a lot on this design with Jeremy, so it's your call whether we should make a change here, and if so what that change would be.

**Comment by johnpryan** [comment] 2021-02-19 23:06
The app bar starts to have issues when the page is too small, so I'm hesitant to add this to the app bar.

**Comment by CalidumCanis** [comment] 2022-01-17 14:17
Maybe add a bit of a gap before the first line of code?

**Comment by CalidumCanis** [comment] 2022-01-17 14:33
Another idea is to add the run button down, and leave some gap after the code:

![image](https://user-images.githubusercontent.com/74233464/149788625-0f047010-30c4-44bd-a58c-d954840961c7.png)

**Comment by parlough** [comment] 2024-06-17 19:16
Thanks for the issue! I'm going to close as a duplicate of https://github.com/dart-lang/dart-pad/issues/1381 which also discusses the same concern.

**Closed by parlough** 2024-06-17 19:16 UTC
Labels: P2, type-polish, type-ux
