### ISSUE TITLE
Possible bug in Element.documentOffset

### ISSUE THREAD

**Issue by ghost** [dart-lang/dart-pad#741] opened 2016-09-05 17:56 UTC
https://dartpad.dartlang.org/a02bb87e98ca42dbb086cc4ce988d2bb

Explanation: The little purple box is supposed to be in the upper-left corner of the green element because I am giving it the 'documentOffset.x and documentOffset.y' properties.
Somehow it won't go there, I've posted a stackoverflow question which advised to report it as a bug.

**Comment by zoechi** [comment] 2016-09-05 19:04
See also http://stackoverflow.com/questions/39333791/element-offset-element-documentoffset-resulten-in-false-values

**Comment by RedBrogdon** [comment] 2019-04-22 16:24
Judging by the SO post and the code, this is was intended to be a Dart SDK bug report. Closing here; please reopen in the SDK issues tracker (https://github.com/dart-lang/sdk/issues) if it's still a problem.

**Closed by RedBrogdon** 2019-04-22 16:24 UTC
Labels: p2
