### ISSUE TITLE
Cannot use Tab key to indent code

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/dart-pad#2918] opened 2024-03-28 22:03 UTC
## What happened?

When entering code and pressing the Tab key to indent the code it does not indent the code. Instead, it moves the focus elsewhere.

## Steps to reproduce problem

1. Enter code in the code editor
2. Press the Tab key to indent a line
3. See that it didn't indent the line.

### Browser

Browser: Chrome

Version: 123.0.6312.59

### Machine

Operating system: MacOS

Version: 14.4

**Comment by parlough** [comment] 2024-03-30 00:53
Duplicate of https://github.com/dart-lang/dart-pad/issues/2852

**Closed** 2024-03-30 00:53 UTC
