### ISSUE TITLE
Save the user's snippet to local storage

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#3016] opened 2024-06-18 21:14 UTC
We should consider implementing the old behavior where closing the browser tab and re-opening DartPad in a new tab shows the snippet that the user was previously editing. 

Currently, the only way to preserve a DartPad snippet is to create a gist.

**Comment by parlough** [comment] 2024-06-18 21:26
Closing as a duplicate of https://github.com/dart-lang/dart-pad/issues/2871

**Closed by parlough** 2024-06-18 21:26 UTC
Labels: type-enhancement, P2
