### ISSUE TITLE
Add `shared_preferences` package

### ISSUE THREAD

**Issue by krjw-eyev** [dart-lang/dart-pad#2305] opened 2022-06-20 14:44 UTC
I have used `shared_preferences` a lot lately and it would be great to test small thing with it via dartpad. Since `shared_preferences` supports web I think this should be a great addition to the already supported packages.

**Comment by domesticmouse** [comment] 2023-01-11 22:50
I'd wonder if this will work in the sandbox iframe. It may work for a session and then disappear, or not work at all.

**Comment by johnpryan** [comment] 2023-01-12 22:03
Closed in #995

**Comment by domesticmouse** [comment] 2023-01-12 22:37
Actually, this isn't shipped to production, so I'm re-opening this issue. This package has been shipped to our hidden testing instance https://dartpad.dev/?channel=dev

Please exercise your suggested package on this instance and confirm here that it works as intended. If you do confirm this as working I'll ship it to `stable`, `beta`, `master`, and `old` channels on dartpad.dev. If you don't confirm, I won't ship it.

**Closed** 2023-01-25 10:03 UTC
Labels: suggested-package
