### ISSUE TITLE
DartPad backend runs out of space on fs

### ISSUE THREAD

**Issue by lambdabaa** [dart-lang/dart-pad#1083] opened 2019-05-28 17:42 UTC
Simply opening DartPad today and pressing run results in

```
Error compiling to JavaScript:
FileSystemException: Creation of temporary directory failed, path = '/tmp/dartpad' (OS Error: No space left on device, errno = 28)
```

![u9VATVvcpAq](https://user-images.githubusercontent.com/535859/58499440-047c1000-8135-11e9-908e-22ef447230b4.png)

**Comment by domesticmouse** [comment] 2019-05-28 22:41
We have temporarily fixed this by rolling the instances, but we still need to find the underlying cause. I'm leaving this open until we find the root cause.

**Comment by RedBrogdon** [comment] 2019-06-17 21:32
@domesticmouse Just checking in -- how are the latest instances doing?

**Comment by domesticmouse** [comment] 2019-06-17 22:41
By my calcs, the instances have been up for six days, and the disk usage is sitting at about 37%, up from 30% when new. I expect I will be rolling these instances for new version updates before they make it out to the full automatic retirement age, but at the current burn rate I'm no longer worried. I think we can close this out now.

**Comment by Jongbloed** [comment] 2019-10-01 14:25
![image](https://user-images.githubusercontent.com/19710734/65971105-f97d1780-e467-11e9-8c54-261c86aa9428.png)
I'm getting this issue today

**Comment by RedBrogdon** [comment] 2019-10-01 22:56
Reported by @johnpryan as well.

**Comment by domesticmouse** [comment] 2019-10-01 23:09
Sadly, I have two old instances I can't ssh into to see what the deal is, but the new instances have empty `/tmp` directories. We can paper over this by upping the disk size yet further, or we can add tasks to the backlog to split up the dart-services server into different servers for each API call, thus enabling us to find out which one is actually leaking.

**Comment by domesticmouse** [comment] 2020-03-25 20:03
We haven't seen this issue for a while.

**Closed by domesticmouse** 2020-03-25 20:03 UTC
Labels: bug, dart-services, p0
