### ISSUE TITLE
Missing concrete implementation of 'StatelessWidget.build' - line 26

### ISSUE THREAD

**Issue by ephraimilunga** [dart-lang/dart-pad#1579] opened 2020-06-15 21:42 UTC
## What happened?

MIssing of an opening curly braces. 

### Browser

Browser: all

Version: all

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
errorMissing concrete implementation of 'StatelessWidget.build' - line 26
errorA class declaration must have a body, even if it is empty - line 26
errorExpected a method, getter, setter or operator declaration - line 37

```

### Machine

Operating system: all 

Version: all

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```
https://dartpad.dev/99243efc05f92cd541af5e279c012050
```

### DartPad's output

None

```
Error compiling to JavaScript:
/tmp/dartpadLLNBSL/main.dart:26:31: Error: A class declaration must have a body, even if it is empty.
Try adding an empty body.
class FriendlyChatApp extends StatelessWidget
                              ^^^^^^^^^^^^^^^
/tmp/dartpadLLNBSL/main.dart:37:1: Error: Expected a declaration, but got '}'.
}
^
/tmp/dartpadLLNBSL/main.dart:26:7: Error: The non-abstract class 'FriendlyChatApp' is missing implementations for these members:
 - StatelessWidget.build
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class FriendlyChatApp extends StatelessWidget
      ^^^^^^^^^^^^^^^
flutter/packages/flutter/lib/src/widgets/framework.dart:700:10: Context: 'StatelessWidget.build' is defined here.
  Widget build(BuildContext context);
         ^^^^^
![Screenshot 2020-06-15 at 23 42 23](https://user-images.githubusercontent.com/26764665/84709069-e82a5b80-af61-11ea-9762-8fe5c96c7c81.png)

```

If you were running Flutter code, you can also paste an image of the
Flutter output directly into this bug report.

**Comment by domesticmouse** [comment] 2020-06-16 01:34
You are missing an opening `{` on your class declaration line. Try the following:

```
class FriendlyChatApp extends StatelessWidget {
```

**Comment by ephraimilunga** [comment] 2020-06-19 23:36
@domesticmouse this error is from the CodeLab side no mine. You get the error straight away when you click on the link to the code from https://dartpad.dev/99243efc05f92cd541af5e279c012050 .

**Comment by domesticmouse** [comment] 2020-06-20 00:30
Thanks for the clarification @ephraimilunga 

@sfshaza2 I believe this is yours to fix =)

**Comment by domesticmouse** [comment] 2020-06-20 00:35
Closing this as a dupe of https://github.com/flutter/website/issues/4248

Thanks again @ephraimilunga =)

**Closed by domesticmouse** 2020-06-20 00:35 UTC

**Comment by ephraimilunga** [comment] 2020-06-20 08:56
It's a pleasure @domesticmouse.
