### ISSUE TITLE
IDE integration for DartPad

### ISSUE THREAD

**Issue by James-Parsons** [dart-lang/dart-pad#174] opened 2015-03-25 17:15 UTC
This may seem weird to people, but it would be nice to be able to import a DartPad code into an Eclipse or WebStorm. That way, If you are using DartPad to help you quickly tweak your code, you can sync your changes with your IDE. I know this is an odd feature request, and probably will not be at the top of your list, but I wouldn't mind forking, working it, and then eventually creating a pull request.

**Comment by sethladd** [comment] 2015-03-25 17:31
Totally not weird. Love the idea! We want to make it really easy to "upgrade" to WebStorm, or Sublime, or a full Dart project.

**Comment by lukechurch** [comment] 2015-03-25 18:05
>but I wouldn't mind forking, working it, and then eventually creating a pull request.

That'd be great! I don't think it's top on the list for either me or @devoncarew so I'm sure a patch would be very welcome.

**Comment by seaneagan** [comment] 2015-03-25 19:26
For the "upgrade" use case, they are just gists, which are just git repos, so it should work in any editor that supports git, right?  Just need to change your remote after cloning to whatever long term git repo you want to use.

**Comment by devoncarew** [comment] 2015-03-25 20:11
We definitely want to make it easy to play with something in dartpad and then import it into a full-blown IDE. That may be clone-and-modify. The gist UI also supports downloading the gist as a zip. That could be the easiest path to getting the code. We plan to create full pub packages* when we save the gists, even if we only show the dart, html, and css code.

*modulo the fact that gists don't support creating directories.

**Comment by devoncarew** [comment] 2015-03-25 20:13
@James-Parsons, the code to create a 'packagified' gist isn't written; perhaps that would be a good place to contribute?

**Comment by devoncarew** [comment] 2015-06-10 19:25
dupe of #428

**Closed by devoncarew** 2015-06-10 19:25 UTC
