### ISSUE TITLE
When DartPad loads, please focus on the source code pane

### ISSUE THREAD

**Issue by eernstg** [dart-lang/dart-pad#3003] opened 2024-06-13 11:48 UTC
## Issue: Useless initial focus

To reproduce: Load 'dartpad.dev' in a browser, press 'c': Nothing happens.

Expected: 'c' would be added to the source code pane.

Known workaround: Pressing TAB 6 times moves the focus to the source code pane. Alternative: Click in the source code pane.

I believe the TAB workaround did not work at some point in time, and that was with the new DartPad, but it does seem to work now. Still, it would be convenient if the focus could be on the source code pane at the beginning&mdash;the entity that currently has the initial focus does not seem to do anything at all, which seems to imply that it isn't a useful choice for any user or any purpose.

### Browser

Browser: Chrome

Version: 125.0.6422.144

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)? No

Are there any warnings or errors in your browser's JavaScript console? No

### Machine

Operating system: Mac

Version: 14.5

**Comment by parlough** [comment] 2024-06-17 20:05
I think focusing the editor on initial load makes sense. Or adding a "Skip to editor" hidden button like many web pages have to skip to the main content.

Closing as a duplicate of https://github.com/dart-lang/dart-pad/issues/2865

**Closed by parlough** 2024-06-17 20:05 UTC
