### ISSUE TITLE
Spacebar opens new project menu

### ISSUE THREAD

**Issue by duck-dev-go** [dart-lang/dart-pad#2907] opened 2024-03-20 09:39 UTC
## What happened?

Pressing spacebar while the code text field is focussed wil open the new project menu. So I can't type spaces in my code.

## Steps to reproduce problem

Press spacebar while writing code.

### Browser

Browser: Google Chrome

Version: Version 122.0.6261.129 (Official Build) (arm64)

Are you using any extensions/plugins that affect website behavior: No

### Machine

Operating system: MacOS

Version: Sonoma 14.4

**Comment by Jordan-Nelson** [comment] 2024-03-20 21:40
I ran into this issue as well. I was able to "fix" it by tapping tab until I was focused on the text editor again. It seems like somehow I had focus on both the menu bar and the text editor. My cursor was showing in the text editor but when I tapped space or return, the menu was interacted with.

I am not sure how to reproduce this after resolving it by tabbing to the text editor.

**Comment by eernstg** [comment] 2024-03-21 10:27
Duplicate of https://github.com/dart-lang/dart-pad/issues/2852?

**Comment by ReinisSprogis** [comment] 2024-03-25 15:29
For me it's `Enter` Cannot go to new line.

**Comment by parlough** [comment] 2024-03-30 00:53
Thanks for the issue and details! It's appreciated.

I'm going to close this as a duplicate of https://github.com/dart-lang/dart-pad/issues/2852 to consolidate tracking of the issue.

**Closed by parlough** 2024-03-30 00:53 UTC
