### ISSUE TITLE
Share button is broken

### ISSUE THREAD

**Issue by zoechi** [dart-lang/dart-pad#806] opened 2018-03-20 13:25 UTC
Previously it opened a dialog that allowed to copy a share URL,
now it navigates to https://github.com/dart-lang/dart-pad/wiki/Sharing-Guide

**Comment by mit-mit** [comment] 2018-03-20 14:17
Thanks for reporting! Yes, we got impacted by GitHub [deprecating anonymous gists](https://blog.github.com/2018-02-18-deprecation-notice-removing-anonymous-gist-creation/). #805 tracks bringing reenabling a sharing flow via an auth flow. Closing this bug as for now the button works as intended.

**Closed by mit-mit** 2018-03-20 14:17 UTC
