### ISSUE TITLE
Gist Multi File Support

### ISSUE THREAD

**Issue by MelbourneDeveloper** [dart-lang/dart-pad#2387] opened 2022-10-09 01:06 UTC
Gists now support multiple files. It would be really awesome if Dartpad could include these files so we can import them. This is almost as good as referencing packages from Pub Dev

Here is an [example gist](https://gist.github.com/MelbourneDeveloper/a0b74ffad825ca6c2224ac84e1d58614) that has two files:

Here is the [Dartpad link](https://dartpad.dev/?id=a0b74ffad825ca6c2224ac84e1d58614)

But I get this error
<img width="437" alt="image" src="https://user-images.githubusercontent.com/16697547/194732813-050cf104-d929-4375-9b88-b2a9ed024cc1.png">

**Comment by parlough** [comment] 2022-10-09 01:13
Thanks for opening an issue! Definitely would be nice to see multiple Dart file support. The necessary work is being tracked in https://github.com/dart-lang/dart-pad/issues/2149.

Duplicate of https://github.com/dart-lang/dart-pad/issues/2149

**Closed by parlough** 2022-10-09 01:13 UTC
