### ISSUE TITLE
"Script error" on dartpad while experimenting with extension type around the 2-tuple

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/dart-pad#2919] opened 2024-03-29 01:48 UTC
I'm trying to implement a type representing a value OR an error.
Tested on dartpad.dev (all channels). The analyzer doesn't report any errors but when I run it, the backend returns "script error".
(The program is probably buggy, but "script error" doesn't tell me where the problem is).

```dart
// definitions
extension type Maybe<T>((T? v, Exception? e) pair) {
  Exception? get error => pair.$2;
  T get value =>
      error != null ? pair.$1 as T : throw "no value, check the error";
}
Maybe<T> ok<T>(T val) => Maybe((val, null));
Maybe<Never> error(String msg) => Maybe((null, Exception(msg)));

// returning Maybe from function
Maybe<int> foo(String msg) {
  return (msg == "Hello") ? ok(1) : error("wrong parameter");
}
// testing it
main() {
  var x = foo("Hello");
  var y=foo("");
  x.value;
  y.value; // expected to throw
}
```

**Comment by eernstg** [comment] 2024-03-29 11:45
I think this is a duplicate of https://github.com/dart-lang/dart-pad/issues/2742.

**Comment by parlough** [comment] 2024-03-29 15:07
Yep. Duplicate of https://github.com/dart-lang/dart-pad/issues/2742

**Closed by parlough** 2024-03-29 15:07 UTC
