### ISSUE TITLE
VIM Mode

### ISSUE THREAD

**Issue by prabinlamsal19** [dart-lang/dart-pad#3038] opened 2024-08-08 05:59 UTC
Is it feasible for the team to create a VIM mode for this editor? If yes, I will try to send pr here only. If not , I will fork this and host that separately. 
Thanks for your time for answering these questions.

**Comment by brainwo** [comment] 2024-08-10 22:17
Duplicate of https://github.com/dart-lang/dart-pad/issues/2902
Please check that issue

**Closed** 2024-08-18 09:09 UTC
Labels: closed-duplicate, type-ux
