### ISSUE TITLE
Load exercises from a repo in addition to gists

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1096] opened 2019-06-05 14:31 UTC
This involves a few individual tasks:

- Create a format for storing multiple DartPad exercises in a single repo.
- Add a RepoController or something similar to dart-pad that's capable of loading data from a repo set up with that format
- Update the new embed UI and playground UI with query string parameters and have them use the RepoController to fetch and parse exercises when supplied with those parameters.

q.v. GitHub's API docs for retrieving repo contents: https://developer.github.com/v3/repos/contents/

**Comment by kwalrath** [comment] 2019-08-02 21:00
Would it be possible to load code from part of a doc repo? I'd love to be able to host DartPad code under https://github.com/dart-lang/site-www/tree/master/examples, so that our site tests can detect when the DartPad code needs to be updated.

**Comment by RedBrogdon** [comment] 2019-10-02 20:34
Fixed for the new embeds by #1295.

**Comment by rrousselGit** [comment] 2020-03-25 06:51
> Fixed for the new embeds by #1295.

Does that mean this is done?
If so, how can we use it?

I would like to embed dart-pad in a blog-post. But having to maintain gists is a hassle, and feels off when the article is written in markdown

**Comment by RedBrogdon** [comment] 2020-03-25 17:58
I should have linked everybody to the wiki page we have for this:

https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide#query-parameters

There are a number of ways to get code into an embedded editor. @johnpryan wrote a script that can detect and transform markdown blocks into iframes, and it's possible to load directly from a repo by creating a small metadata file for each exercise you want to load.

One feature we still haven't implemented is a hardcoded GitHub path to a single file. That feature request remains outstanding.

**Comment by parlough** [comment] 2024-05-06 09:50
Closing this as a duplicate of https://github.com/dart-lang/dart-pad/issues/1763."

Note that the workshop feature discussed in that issue is no longer supported. Feel free to explore other open issues like https://github.com/dart-lang/dart-pad/issues/2702 that explore alternatives.

**Closed by parlough** 2024-05-06 09:50 UTC
Labels: type-enhancement, P1
