### ISSUE TITLE
Uncaught Error: Unsupported operation: StdIOUtils._getStdioInputStream

### ISSUE THREAD

**Issue by harikanani** [dart-lang/dart-pad#1511] opened 2020-03-23 04:36 UTC
when i'm trying to input from user through console it will give me an error in dartpad online.

my code is here.

`import 'dart:io';
void main() {
  print("Enter Percentages:");
  int n = int.parse(stdin.readLineSync());
  int percentage = int.parse(stdin.readLineSync());
  print(n);
  print(percentage);
}`

and it Give the Error : 
`Uncaught Error: Unsupported operation: StdIOUtils._getStdioInputStream`

**Comment by RedBrogdon** [comment] 2020-03-24 22:32
The dart:io library is not intended for use in web browsers, which is why this code is failing. See the Dart API doc here:

https://api.dart.dev/stable/2.7.2/dart-io/dart-io-library.html

The message DartPad prints when the library is used is not ideal, though, so thanks for letting us know. We should improve it as part of fixing #857 (I'm going to close this issue as a duplicate of that one).

**Closed by RedBrogdon** 2020-03-24 22:32 UTC

**Comment by D2500683** [comment] 2024-01-05 15:32
I am still having the same issue on Dartpad.
Here is m Code:
import "dart:io";
void main(){
  print("What is our name?");
  String username = stdin.readLineSync()!;
  print('hi ${username}, you are welcome');
}
and it gave the error:
Uncaught Error: Unsupported operation: StdIOUtils._getStdioInputStream
