### ISSUE TITLE
Page freeze

### ISSUE THREAD

**Issue by Adamovskiy** [dart-lang/dart-pad#753] opened 2017-01-17 11:20 UTC
Executing this code
```dart
void main() {
	String str = '''
@Component(
    selector: 'channels-editor',
    templateUrl: 'sale_detail_component.html')
class SaleDetailComponent extends BaseChannelsEditor  {
}
  ''';
  print(str.replaceAllMapped(new RegExp('@Component(.*\\n*)*class\\s+(\\S+)\\s+(extends\\s+\\S+\\s+)?(with\\s+\\S+\\s+)?', multiLine: true, caseSensitive: false), (match)=>"##" ));
}
```
leads to page freeze with no output and no errors.

**Comment by lukechurch** [comment] 2017-10-31 14:56
This appears to be a duplicate of https://github.com/dart-lang/dart-pad/issues/384.

If you run the same code in the terminal it doesn't terminate. We might need to come up with a better UI for handling this, but it's non-trivial to do so.

**Closed by lukechurch** 2017-10-31 14:56 UTC
