### ISSUE TITLE
Find a solution to cache invalidation issue

### ISSUE THREAD

**Issue by spencerchubb** [dart-lang/dart-pad#1680] opened 2020-11-19 22:59 UTC
## What happened?

Layout is off and no code will compile
![image](https://user-images.githubusercontent.com/58525483/99734259-7adea180-2a90-11eb-88e0-d9f0ed2bdb77.png)

## Steps to reproduce problem

Open dartpad.dev

### Browser

Browser: Chrome

Version:

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

DevTools failed to load SourceMap: Could not load content for https://dartpad.dev/scripts/playground.dart.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

DevTools failed to load SourceMap: Could not load content for https://dartpad.dev/split.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Machine

Operating system: Windows 10

Version:

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```
// Paste code here.
```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```
[paste console output here]
```

If you were running Flutter code, you can also paste an image of the
Flutter output directly into this bug report.

**Comment by nekoto-kun** [comment] 2020-11-20 03:12
Same here. Dartpad getting error in console.

![image](https://user-images.githubusercontent.com/40553075/99753424-c50b6580-2b18-11eb-9f37-683ebd76ff8f.png)

**Comment by nekoto-kun** [comment] 2020-11-20 03:14
Dartpad in this link is working: https://dartpad.dartlang.org/
What is going on with https://dartpad.dev?

**Comment by RedBrogdon** [comment] 2020-11-20 06:05
This is a caching issue that occasionally pops up when we update the HTML that DartPad uses. The serving setup we use for the front-end of DartPad will, for some users, serve the *old* HTML with the *new* JavaScript. After a few hours, all the caches have invalidated the old HTML and the problem fades away.

By now, this should no longer be an issue, but I'm going to retitle and maintain this issue, since we do need to address the root cause going forward.

**Comment by johnpryan** [comment] 2020-12-02 22:35
I think this would fix the issue: https://github.com/dart-lang/dart-pad/issues/1683. I'm going to close this so we can track it there.

**Closed by johnpryan** 2020-12-02 22:35 UTC
