### ISSUE TITLE
Possible type mismatch or NNBD mode issue with Firebase gist

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1947] opened 2021-07-01 04:53 UTC
This gist:

https://dartpad.dev/c21e00325f9269f0730a28df473f841c?null_safety=true

Currently produces this error when compiled and executed for a second time:

```
Uncaught (in promise) Error: Expected a value of type 'App?', but got one of type 'App'
    at Object.throw_ [as throw] (storage.googleapis.com/nnbd_artifacts/2.13.3/dart_sdk.js:5041)
    at Object.castError (storage.googleapis.com/nnbd_artifacts/2.13.3/dart_sdk.js:5014)
    at Object.cast [as as] (storage.googleapis.com/nnbd_artifacts/2.13.3/dart_sdk.js:5323)
    at dart.NullableType.new.as (storage.googleapis.com/nnbd_artifacts/2.13.3/dart_sdk.js:6830)
    at Expando.new._get (storage.googleapis.com/nnbd_artifacts/2.13.3/dart_sdk.js:118824)
    at Function.getInstance (<anonymous>:738:15)
    at MappedListIterable.new.<anonymous> (<anonymous>:3513:78)
    at MappedListIterable.new.elementAt (storage.googleapis.com/nnbd_artifacts/2.13.3/dart_sdk.js:22034)
    at ListIterator.new.moveNext (storage.googleapis.com/nnbd_artifacts/2.13.3/dart_sdk.js:21840)
    at JsIterator.next (storage.googleapis.com/nnbd_artifacts/2.13.3/dart_sdk.js:6709)
    at Function.of (storage.googleapis.com/nnbd_artifacts/2.13.3/dart_sdk.js:43331)
    at MappedListIterable.new.toList (storage.googleapis.com/nnbd_artifacts/2.13.3/dart_sdk.js:21653)
    at Object.get apps [as apps] (<anonymous>:3513:198)
    at Object.main$0 [as main] (<anonymous>:607:19)
    at main$ (<anonymous>:579:12)
    at main$.next (<anonymous>)
    at storage.googleapis.com/nnbd_artifacts/2.13.3/dart_sdk.js:37403
    at _RootZone.runUnary (storage.googleapis.com/nnbd_artifacts/2.13.3/dart_sdk.js:37274)
    at _FutureListener.thenAwait.handleValue (storage.googleapis.com/nnbd_artifacts/2.13.3/dart_sdk.js:32530)
    at handleValueCallback (storage.googleapis.com/nnbd_artifacts/2.13.3/dart_sdk.js:33057)
    at Function._propagateToListeners (storage.googleapis.com/nnbd_artifacts/2.13.3/dart_sdk.js:33095)
    at _Future.new.[_completeWithValue] (storage.googleapis.com/nnbd_artifacts/2.13.3/dart_sdk.js:32943)
    at storage.googleapis.com/nnbd_artifacts/2.13.3/dart_sdk.js:32194
    at _RootZone.runUnary (storage.googleapis.com/nnbd_artifacts/2.13.3/dart_sdk.js:37274)
    at _FutureListener.then.handleValue (storage.googleapis.com/nnbd_artifacts/2.13.3/dart_sdk.js:32530)
    at handleValueCallback (storage.googleapis.com/nnbd_artifacts/2.13.3/dart_sdk.js:33057)
    at Function._propagateToListeners (storage.googleapis.com/nnbd_artifacts/2.13.3/dart_sdk.js:33095)
    at _Future.new.[_completeWithValue] (storage.googleapis.com/nnbd_artifacts/2.13.3/dart_sdk.js:32943)
    at async._AsyncCallbackEntry.new.callback (storage.googleapis.com/nnbd_artifacts/2.13.3/dart_sdk.js:32964)
    at Object._microtaskLoop (storage.googleapis.com/nnbd_artifacts/2.13.3/dart_sdk.js:37526)
    at _startMicrotaskLoop (storage.googleapis.com/nnbd_artifacts/2.13.3/dart_sdk.js:37532)
    at storage.googleapis.com/nnbd_artifacts/2.13.3/dart_sdk.js:33303
```

**Comment by srawlins** [comment] 2021-07-01 13:36
Duplicate of https://github.com/dart-lang/dart-pad/issues/1912

**Closed by srawlins** 2021-07-01 13:36 UTC
Labels: firebase, p1
