### ISSUE TITLE
Rendering problem in Chrome Canary

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1395] opened 2019-11-22 23:30 UTC
1. Go to the exceptions code example in the cheatsheet codelab:
https://dart.dev/codelabs/dart-cheatsheet#code-example-9
1. Click the Solution tab and confirm that you want to show the solution.
1. Copy the solution code. (Either select-all and copy on the keyboard or clicking the copy icon works.)
1. Go back to the Dart tab, and select all the code.
Paste the solution code into the Dart tab.

![image](https://user-images.githubusercontent.com/1145719/69467483-0833cc80-0d3d-11ea-92ab-a13070efb31a.png)

**Comment by kwalrath** [comment] 2019-11-22 23:33
I can repro in Canary but not Stable Google Chrome.

**Comment by kwalrath** [comment] 2019-11-25 22:53
I'm seeing a similar rendering issue for the iterables codelab, and I didn't even interact (much) with the code:

![image](https://user-images.githubusercontent.com/2164483/69584788-e6cc1e00-0f92-11ea-94b3-e5f105e6ce1a.png)

To reproduce, use Canary to go to https://mb-dart-dev-1.firebaseapp.com/codelabs/iterables#example-using-iterator-and-for-in-loop, and try to scroll the code. In a fresh window, I can't see anything below the top half of line 21, but the top matter IS appearing.

**Comment by domesticmouse** [comment] 2019-11-25 23:56
I'd be interested to know if this failure is reproducible with Flutter for web. That way we know if it is a Flutter for web issue, or if it is something we are introducing in `dart-pad` and/or `dart-services`.

The version of Flutter that is deployed in the serving is https://github.com/flutter/flutter/tree/fbabb264e0ab3e090d6ec056e0744aaeb1586735, which is about 24 days behind master. We can bring it closer to head, but there are stability risks. We need to find a good PR to migrate to.

**Comment by RedBrogdon** [comment] 2019-11-26 17:16
We've had rendering issues with Canary before (#914), and they didn't end up repro-ing after the Canary version made it to stable release.

Is it possible there's something intrinsic to the way the canary version is built that's throwing us off? Could we contact the Chrome team and get some advice here?

**Comment by domesticmouse** [comment] 2019-11-26 20:45
It's also a problem in Chrome 79 (beta) which according to https://www.chromestatus.com/features/schedule is due to become stable in 13 days.

**Comment by parlough** [comment] 2024-02-18 03:02
There haven't been more updates here since 2019 and the issues were appearing on nightly versions of Chrome, so I'm going to close this for now. If anyone experiences new issues with any supported browsers (latest 2 versions), please open a new issue with details. Thanks!

**Closed by parlough** 2024-02-18 03:02 UTC
Labels: type-bug, P2
