### ISSUE TITLE
give us option to open a single file in a gist using 'dartpad.dev/#gistid' method the gists as a folder for codes (of each file)

### ISSUE THREAD

**Issue by KarthiDreamer** [dart-lang/dart-pad#2380] opened 2022-10-04 10:38 UTC
**This may help  us better organize gist in a folder and file hierarchy in which I can store multiple files in a single gist.**

For example: 
Take this example gist:          " https://gist.github.com/KarthiDreamer/4fd4e1cd6ae1d669eb59c9091e4f6bb9 "

The gist has 2 files, one has main function and the other one has a simple print function ,
And I found that when I tried to convert it to dartpad file,

![image](https://user-images.githubusercontent.com/84800257/193798013-4600f14f-0d2e-49f5-974e-4df22d204092.png)
I cannot use this gist in dartpad.dev and it says It cannot find a main function even thought one of them has a main function.

I also found  that each of the files in the gist do  have a unique guest id if we tap its file name
File 1 - https://gist.github.com/KarthiDreamer/4fd4e1cd6ae1d669eb59c9091e4f6bb9#file-async_await-dart
File 2 - https://gist.github.com/KarthiDreamer/4fd4e1cd6ae1d669eb59c9091e4f6bb9#file-somerandom-dart

Use these features to make gist a folder and the files as a induvidual dart code

**Comment by johnpryan** [comment] 2022-10-05 23:09
Duplicate of #2149

**Closed** 2022-10-05 23:35 UTC
Labels: enhancement
