### ISSUE TITLE
Closing window does not persist state

### ISSUE THREAD

**Issue by craiglabenz** [dart-lang/dart-pad#2908] opened 2024-03-20 15:26 UTC
Accidentally closing the DartPad window does not seem to automatically persist state for the next session, leading to the possibility of lost work.

Could each keystroke be saved to local storage?

**Comment by parlough** [comment] 2024-03-25 20:14
Thanks for the issue Craig! This is something that's hasn't been implemented with the new UI yet, but I agree it should be reimplemented to support user's expectations.

Closing as a duplicate of https://github.com/dart-lang/dart-pad/issues/2871.

**Closed by parlough** 2024-03-25 20:14 UTC
