### ISSUE TITLE
Dart pad not showing anything in Brave Browser

### ISSUE THREAD

**Issue by sakarayajitesh** [dart-lang/dart-pad#1583] opened 2020-06-26 10:55 UTC
![dart](https://user-images.githubusercontent.com/22650227/85850036-a7380f80-b7c9-11ea-9cc6-7e786a587097.png)

**Comment by RedBrogdon** [comment] 2020-06-27 00:28
Thanks for filing an issue!

The Brave browser includes a number of additional restrictions for iframes and cross-origin requests that cause DartPad to fail. It's a known issue that we haven't had the engineering bandwidth to address.

Closing as a duplicate of #1410.

**Closed by RedBrogdon** 2020-06-27 00:28 UTC
